### ISSUE TITLE
[Zola Goodies] Copy Code Button and Sortable Tables

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [getzola/zola#1019]
## Copy Code Button

I have been struggling hard on how to make a copy code button for codefences in zola. It's easier to do in hugo because code is placed in a code tag inside a pre tag but because of the way zola renders codefences as multiple span blocks, which I prefer, it's less obvious to me on how to go about doing this. I do think this would be something valuable to have in the documentation.

## Sortable Tables

I figured this one out with a lot of googling, I am not a web developer so there's definitely a better way of doing this but this works for my use case. Sorting came from [w3schools](https://www.w3schools.com/howto/howto_js_sort_table.asp). This will work with multiple tables and only sorts alphabetically when the header is clicked on. I think this would good to have in the zola documentation but I would be interested in what other people think.

```js
function sortTables() {
    document.querySelectorAll('table').forEach(function (table) {

        for (let i = 0; i < table.children[0].children[0].cells.length; i++) {
            table.children[0].children[0].cells[i].addEventListener('click', function () {
                sortTable(table, i)
            });
        }
    });
}

function sortTable(table, n) {
    var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
    switching = true;
    // Set the sorting direction to ascending:
    dir = "asc";
    /* Make a loop that will continue until
    no switching has been done: */
    while (switching) {
        // Start by saying: no switching is done:
        switching = false;
        rows = table.rows;
        /* Loop through all table rows (except the
        first, which contains table headers): */
        for (i = 1; i < (rows.length - 1); i++) {
            // Start by saying there should be no switching:
            shouldSwitch = false;
            /* Get the two elements you want to compare,
            one from current row and one from the next: */
            x = rows[i].getElementsByTagName("TD")[n];
            y = rows[i + 1].getElementsByTagName("TD")[n];
            /* Check if the two rows should switch place,
            based on the direction, asc or desc: */
            if (dir == "asc") {
                if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                    // If so, mark as a switch and break the loop:
                    shouldSwitch = true;
                    break;
                }
            } else if (dir == "desc") {
                if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                    // If so, mark as a switch and break the loop:
                    shouldSwitch = true;
                    break;
                }
            }
        }
        if (shouldSwitch) {
            /* If a switch has been marked, make the switch
            and mark that a switch has been done: */
            rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
            switching = true;
            // Each time a switch is done, increase this count by 1:
            switchcount++;
        } else {
            /* If no switching has been done AND the direction is "asc",
            set the direction to "desc" and run the while loop again. */
            if (switchcount == 0 && dir == "asc") {
                dir = "desc";
                switching = true;
            }
        }
    }
}

document.addEventListener('DOMContentLoaded', function() {
    sortTables();
});
```

## Terminal/Command Prompt commands

I have this shortcode that I love for linux command line instructions

`shortcodes/cli.html`

```html
<pre class="cli"><code><ul class="cli"><li>{{ body | safe }}</li></ul></code></pre>
<br />
```

`cli.scss`

```scss
pre {
    white-space: pre-wrap;
    tab-size: 4;
    border-radius: $radius-large;
    font-family: $family-code;

    &.cli {
        background-color: #292B2E;

        code {
            ul.cli {
                margin-left: 2em;
                margin-top: -.15em;
                list-style: none;
                color: #BC6EC5;
            
                li:before {
                    content: '$';
                    color: #2D9574;
                    font-weight: bold;
                    margin-left: -1em;
                    margin-right: 1em;
                }
            }
        }
    }
}
```

What's cool about it is that it renders like 

```
$ command argument
```

But whenever you highlight the content it highlights everything except for the `$`, I get so annoyed when I try to copy and run content from a site and I have to carefully highlight the commands. 

Anyway I'm not sure if zola would be interested in including this in it's documentation but I am offering.
