### ISSUE TITLE
Feature request: External sources for presenting tabular data

### ISSUE THREAD

**Issue by rcarmo** [getzola/zola#1230]
Hello there,

I've been considering moving to Zola but have a rather large amount of pages that are curated links to resources:

* https://taoofmac.com/space/dev/JavaScript
* https://taoofmac.com/space/dev/Python
* https://taoofmac.com/space/dev/Clojure
* https://taoofmac.com/space/dev/Rust

I currently generate those tables out of YAML files that provide both the data and the headings (so my internal markup is very much like a short code that just says "generate table from this source file").

As an example, here's the first few lines of my Rust page:

```yaml
---
head:
  category: Category
  link: Link
  notes: Notes

ordering: [category, link, notes]
formats:
    link: <a href="{url}">{link}</a>

body:    
- url: https://github.com/rayon-rs/rayon
  link: rayon
  notes: a data parallelism library
  date: 2020-08-29
  category: Parallelism
  
- url: https://github.com/KDE/heaptrack
  link: heaptrack
  notes: a memory profiler
  date: 2020-08-29
  category: Profiling
```

I also do a fair amount of Jupyter/data science stuff, and have always struggled with rendering small snippets of CSV data.

Is any of this planned/of interest?

**Comment by Keats** [comment]
You can already load files via https://www.getzola.org/documentation/templates/overview/#load-data although YAML is not supported. You can also have shortcodes that render markdown (https://www.getzola.org/documentation/content/shortcodes/) which would work in your case I believe?

**Comment by rcarmo** [comment]
Well, I have dozens of tables like that in YAML format, around five in CSV so far and zero in Markdown--they're rendered by custom code...

**Comment by halostatue** [comment]
@rcarmo The python package `remarshal` can convert your YAML to TOML trivially (`yaml2toml`), and I find that TOML is _really_ good for a lot of use cases and may be good for yours.

Your example would be formatted as (this is an automatic conversion, which appears to do key sorting):

```toml
ordering = ["category", "link", "notes"]
[[body]]
category = "Parallelism"
date = 2020-08-29T00:00:00
link = "rayon"
notes = "a data parallelism library"
url = "https://github.com/rayon-rs/rayon"

[[body]]
category = "Profiling"
date = 2020-08-29T00:00:00
link = "heaptrack"
notes = "a memory profiler"
url = "https://github.com/KDE/heaptrack"

[formats]
link = "<a href=\"{url}\">{link}</a>"

[head]
category = "Category"
link = "Link"
notes = "Notes"
```
