### ISSUE TITLE
feature request: Add `skip_paths` option to `link_checker` config

### ISSUE THREAD

**Issue by JohnTitor** [getzola/zola#1259]
Currently, we can ignore some URLs with `skip(_anchor)_prefixes` on the link checker (i.e. `zola check`).
It'd be great if we could also ignore some file paths, like:

```toml
[link_checker]
# Skipping link checks for these relative paths
skip_paths = [
    "content/posts/an-outdated-post.md",
]
```

This is useful when we remain the posts for compatibility but don't want to link-check anymore, for example.
