### ISSUE TITLE
Extra syntax does not seem to work

### ISSUE THREAD

**Issue by tatref** [getzola/zola#1265]
# Bug Report

## Environment

Zola version: 0.12.2 (windows), I also tried with master branch

## Expected Behavior
Load extra syntaxes from `extra_syntaxes` directories and colorise code

## Current Behavior
Code is using the default highlighter (simple monospace font, no colors)

## Step to reproduce
config.toml

```
extra_syntaxes = [
    "syntaxes",
]
```

syntaxes/mylang.sublime-syntax (copy from https://www.sublimetext.com/docs/3/syntax.html, I only replaced "c" by "mylang")
```
%YAML 1.2
---
name: mylang
file_extensions: [mylang]
scope: source.mylang

contexts:
  main:
    - match: \b(if|else|for|while)\b
      scope: keyword.control
```

content/blog/syntax.md

    +++
    title = "syntax"
    slug = "syntax"
    
    date = 2099-01-01
    +++
    
    # Demo
    ```mylang
    for (int i = 0; ; i++ ) {
        if (i < 10) 
    }

    ```c
    for (int i = 0; ; i++ ) {
        if (i < 10) 
    }
    ```

![image](https://user-images.githubusercontent.com/2582791/102717524-39395480-42e3-11eb-9b7e-d84e5836e83f.png)

Digging into the code, is seems that `in_extra` is false
https://github.com/getzola/zola/blob/fce3e4b8a0d04067e4ffc063572872e912dec5dd/components/rendering/src/markdown/codeblock.rs#L28

And `self.Extra_syntax_set` is None
https://github.com/getzola/zola/blob/fce3e4b8a0d04067e4ffc063572872e912dec5dd/components/rendering/src/markdown/codeblock.rs#L43

Am I missing something?

Can you help me to solve this?
