### ISSUE TITLE
New "markdown.highlight_theme" configuration setting clashes with old "highlight_theme" setting

### ISSUE THREAD

**Issue by flother** [getzola/zola#1291]
# Bug report

In v0.13.0 of Zola, if the new `markdown.highlight_theme` configuration setting is set but the old `highlight_theme` setting is left as its default setting, both highlight themes will be used to highlight code.

To reproduce, compile Zola from the HEAD of the [next branch](https://github.com/getzola/zola/tree/next) (I used [commit 74bf676c](https://github.com/getzola/zola/commit/74bf676cede18854c0b44ad8142a961a475bafa3)) and use `zola init` to create a new site. Paste this into `config.toml`:

```toml
# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "solarized-light"

[extra]
# Put all your custom variables here
```

This is the default config for a v0.13.0 site, except code highlighting is turned on and the highlighting theme is set to `solarized-light`. This gives us two settings for code highlighting:

- `highlight_theme = "base16-ocean-dark"` (the default, deprecated, setting)
- `markdown.highlight_theme = "solarized-light"`

If you create a page with a code block (with highlighting), you end up with a mishmash of highlighting. Example:

![zola-highlight-theme](https://user-images.githubusercontent.com/48392/103879398-b3cde680-50cf-11eb-8df4-f1f363c98525.png)

I'm not at all certain, but the [`highlight_theme()` function in `components/config/src/config/mod.rs`](https://github.com/getzola/zola/blob/74bf676cede18854c0b44ad8142a961a475bafa3/components/config/src/config/mod.rs#L194-L202) could be the culprit. It might be that the if statement should be flipped, and `self.markdown.highlight_theme` should be returned if it's set first, before falling back to `self.highlight_theme`.

## Environment

Zola version: v0.13.0, compiled from [commit 74bf676c](https://github.com/getzola/zola/commit/74bf676cede18854c0b44ad8142a961a475bafa3) on the `next` branch.

## Expected behaviour

If `markdown.highlight_theme` is set in `config.toml`, only that setting should be used to highlight Markdown code blocks.

## Current behaviour

If the new `markdown.highlight_theme` setting is set and the deprecated `highlight_theme` is not set, both highlighting themes are used to highlight Markdown code blocks.

## Step to reproduce

See bug report above.
