### ISSUE TITLE
Docker documentation live_reload port

### ISSUE THREAD

**Issue by jmzagorski** [getzola/zola#1345]
# Documentation issue

## Summary
I thought it might be helpful to add a tip in the [Docker Documentation](https://www.getzola.org/documentation/getting-started/installation/#docker) about the live_reload feature of serving a zola site in docker (All credit for this goes to Roman in our [Discord Support Topic](https://zola.discourse.group/t/auto-refreshing-browser-with-docker/773)). To get live reload to work you have to expose the port that live reload is listening on. In many cases this is port 1024, so the new docker run command would be: `$ docker run -u "$(id -u):$(id -g)" -v $PWD:/app --workdir /app -p 8080:8080 -p 1024:1024 balthek/zola:0.13.0 serve --interface 0.0.0.0 --port 8080 --base-url localhost` or if someone is more comfortable with docker-compose:

```
version: "2.4"

services:
  app:
    working_dir: /app
    image: balthek/zola:0.13.0
    container_name: zola_workspace
    command: serve --interface 0.0.0.0 --port 8080 --base-url localhost
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "1024:1024"
```

## Proposed solution
A quick solution would be to mention the above in the documentation and suggest the 1024 port mapping, but that leaves room for error. The code to find the live_reload port looks through 1024..9000, so 1024 might not be the live_reload port. So my next question would be, do you see benefit in printing out the live_reload port to the console with the other information. In docker you might be able to get around not knowing the live_reload port by exposing a range of ports (e.g. 1024-9000), but that might not be realistic (and on my machine docker cannot run with all those port bindings)
