### ISSUE TITLE
Unexpected path collision

### ISSUE THREAD

**Issue by kuon** [getzola/zola#1437]
# Bug Report

## Environment

Zola version: 0.13

I have the current content directory structure (all files with empty frontmatter):

```
.
└── p
    └── ecgs
        ├── 001
        │   ├── index.en.md
        │   └── index.fr.md
        ├── 002
        │   ├── index.en.md
        │   └── index.fr.md
        ├── index.en.md
        └── index.fr.md

4 directories, 6 files
```

I have the following config:

```toml
# The URL the site will be built for
base_url = "https://xxx.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

default_language = "fr"

languages = [
    {code = "en", search = true},
    {code = "de", search = true},
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here


```

When building, I have the following path collision:

```
Building site...
Failed to build the site
Error: Found path collisions:
- `/p/ecgs/index-fr/` from files ["p/ecgs/002/index.fr.md", "p/ecgs/001/index.fr.md"]
```

But I expect the following directory tree to be produced:

```
source - dest
content/p/ecgs/001/index.en.md -> /en/p/ecgs/001.html
content/p/ecgs/002/index.en.md -> /en/p/ecgs/002.html
content/p/ecgs/index.en.md -> /en/p/ecgs.html

content/p/ecgs/001/index.fr.md -> /fr/p/ecgs/001.html
content/p/ecgs/002/index.fr.md -> /fr/p/ecgs/002.html
content/p/ecgs/index.fr.md -> /fr/p/ecgs.html
```
