### ISSUE TITLE
Setting default_language takes no effect

### ISSUE THREAD

**Issue by longfangsong** [getzola/zola#1615]
# Bug Report

## Environment

Zola version:
v0.14.1 (also apply to current `next` branch)

## Expected Behavior

(In fact I'm a little confused about what's the expected behaviour for zola here. I read the doc and some similiar issues like #1512 but still cannot figure it out.)

I suppose setting `default_language` in `config.toml` will make `__tera_context.config.title` to be `[languages.<default_language>.title]`.

## Current Behavior

It seems zola always prefer translations under `en`.

## Step to reproduce

In my `templates/index.html`:

```html
<h1>{{ config.title }}</h1>
```

In `config.toml`:
```toml
# ...
title = "title"
default_language = "fr"
[translations]
title = "translations.title"

[languages.fr]
title = "languages.fr.title"
[languages.fr.translations]
home = "languages.fr.translations.home"

[languages.en]
title = "languages.en.title"
[languages.en.translations]
home = "languages.fr.translations.home"
```

All other files are untouched after `zola init`.

Serve with `zola serve`, the result is `languages.en.title`.

Some behaviour in other situations:

- When all translation and languages stuff removed, ie.
  ```toml
  # ...
  # add or remove `default_language` makes no difference
  # default_language = "fr"
  title = "title"
  ```
  Then the result is nothing (`__tera_context.config.title` is null), is it a regression bug #1512 ?
- When we have `[languages.en]`, ie.
  ```toml
  # ...
  # add or remove `default_language` still makes no difference
  # default_language = "fr"
  [languages.en]
  title = "languages.en.title"
  [languages.en.translations]
  home = "languages.fr.translations.home"
  ```
  Then the result is always `languages.en.title`, no matter what value `default_language` is or other languages configuations added.
