### ISSUE TITLE
Array on config.toml

### ISSUE THREAD

**Issue by sirodoht** [getzola/zola#200]
Hi, just got started with gutenberg; trying to port my Jekyll website.

Is it possible to have a more verbose way to write arrays on the `[extra]` data?

eg: I understand this is valid:
```
[extra]
links = [
    {url = "/", name = "Home"},
    {url = "/about", name = "About"},
    ]
```
I can access it with `config.extra.links`.

However, I want to have something like this:
```
projects = [
    {name = "project 1", url = "https://www.example.com", description = "multiline comment somehow?", many = "more", keys = "and values"},
    {name = "project 2", url = "...", ...},
    ]
```
Is there a better way? Breaking the line after `{` doesn't seem to work.

From the TOML docs I concluded in this, but it does not work either:
```
[extra]
    [[links]]
    url = "/"
    name = "Home"

    [[links]]
    url = "/about"
    name = "About"
```

**Comment by Keats** [comment]
I believe the following should work:

```toml
[extra]
    [[extra.links]]
    url = "/"
    name = "Home"

    [[extra.links]]
    url = "/about"
    name = "About"
```
I'm surprised TOML doesn't allow newlines in objects though, time to write a new config language!
