### ISSUE TITLE
CORS policy; enable setting custom headers or allow defaults for fonts, etc

### ISSUE THREAD

**Issue by andrewzah** [getzola/zola#203]
Access to Font at 'http://127.0.0.1:1111/main.css/fonts/libre/LibreBaskerville-Italic.ttf' from origin 'http://localhost:1111' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1111' is therefore not allowed access. The response had HTTP status code 500.

---

```scss
  @font-face {
    font-family: LibreBaskerville;
    src: url("fonts/libre/LibreBaskerville-Regular.ttf");
    font-weight: normal;
    font-style: normal;
  }
```
