### ISSUE TITLE
Add favicon to config

### ISSUE THREAD

**Issue by KingOfThePirates** [getzola/zola#276]
I added as an extra and it works:

```toml
[extra]
# Put all your custom variables here

favicon = "/favicon/favicon.ico"
```

```html
{% block favicon %}<link rel="icon" href="{{ config.extra.favicon }}">{% endblock favicon %}
```

I'd like to be able to have this in the main config
