### ISSUE TITLE
Base URL with tilde in the path.

### ISSUE THREAD

**Issue by gatoWololo** [getzola/zola#318]
Hello,

I'm using Guttenberg to set up a class website for Upenn's Rust class. The URL that was given to me by our IT department is https://www.seas.upenn.edu/~cis198/ (I cannot change this path).

My `config.toml` has

```toml
base_url = "https://www.seas.upenn.edu/~cis198/"
```

My understanding based on #273 is that `base_url` is supposed to handle paths cleanly, so I can just write:
```toml
[extra]
# Put all your custom variables here
hyde_links = [
    {url = "/", name = "Home"},
```

However, this doesn't seem to work, I need to use:
```toml
[extra]
# Put all your custom variables here
hyde_links = [
    {url = "/~cis198", name = "Home"},
```

To get the expected behavior. I think the tilde is messing up the paths? Or am I thinking of `base_url` wrong?
