### ISSUE TITLE
MiniZinc syntax highlighting

### ISSUE THREAD

**Issue by zayenz** [getzola/zola#372]
I would like to have syntax highlighting for the [MiniZinc language](http://www.minizinc.org), where I think the one from [astenmark/sublime-mzn](https://github.com/astenmark/sublime-mzn) is the currently best available that I've found.

I tried to add it myself using the instructions, but the `generate_sublime` example failed even before adding the new minizinc files on clean copy of the repo at commit 742987144c0b70137fe715a3b4a4d05d01c38220. The following is the error output encountered:

```
$  RUST_BACKTRACE=1 cargo run --example generate_sublime synpack ../../sublime_syntaxes ../../sublime_syntaxes/newlines.packdump ../../sublime_syntaxes/nonewlines.packdump
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `/Users/zayenz/zayenz/projects/gutenberg-projects/gutenberg/target/debug/examples/generate_sublime synpack ../../sublime_syntaxes ../../sublime_syntaxes/newlines.packdump ../../sublime_syntaxes/nonewlines.packdump`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseSyntax(RegexCompileError("(?=\\b@?[A-Z_][A-Z0-9_]*(?=[^\\w-<>=\\$]))", Error(-112, unmatched range specifier in char-class)))', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:463
   5: std::panicking::try::do_call
             at libstd/panicking.rs:350
   6: std::panicking::try::do_call
             at libstd/panicking.rs:328
   7: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10: generate_sublime::main
             at components/highlighting/examples/generate_sublime.rs:27
  11: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  14: std::sys_common::cleanup
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  16: generate_sublime::main
```
For simplicity, I've included the compiled `MZN.sublime-syntax` file that I generated from the above referenced repository below here:

```
%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: MiniZinc (MZN)
file_extensions:
  - mzn
  - dzn
scope: source.mzn
contexts:
  main:
    - match: \%.*
      scope: comment.line.percentage.mzn
    - match: /\*
      push:
        - meta_scope: comment.block.mzn
        - match: \*/
          pop: true
    - match: \'.*?\'
      scope: string.quoted.single.mzn
    - match: \".*?\"
      scope: string.quoted.double.mzn
    - match: \b(ann|annotation|any|constraint|function|in|include|list|of|op|output|minimize|maximize|par|predicate|record|satisfy|solve|test|type|var)\b
      scope: keyword.control.mzn
    - match: \b(array|set|bool|enum|float|int|string|tuple)\b
      scope: storage.type.mzn
    - match: \b(for|forall|if|then|else|endif|where)\b
      scope: keyword.control.mzn
    - match: \b(abort|abs|acosh|array_intersect|array_union|array1d|array2d|array3d|array4d|array5d|array6d|asin|assert|atan|bool2int|card|ceil|concat|cos|cosh|dom|dom_array|dom_size|fix|exp|floor|index_set|index_set_1of2|index_set_2of2|index_set_1of3|index_set_2of3|index_set_3of3|int2float|is_fixed|join|lb|lb_array|length|ln|log|log2|log10|min|max|pow|product|round|set2array|show|show_int|show_float|sin|sinh|sqrt|sum|tan|tanh|trace|ub|ub_array)\b
      scope: entity.name.function.mzn
    - match: \b(circuit|disjoint|maximum|maximum_arg|member|minimum|minimum_arg|network_flow|network_flow_cost|partition_set|range|roots|sliding_sum|subcircuit|sum_pred)\b
      scope: support.function.mzn
    - match: \b(alldifferent|all_different|all_disjoint|all_equal|alldifferent_except_0|nvalue|symmetric_all_different)\b
      scope: support.function.mzn
    - match: \b(lex2|lex_greater|lex_greatereq|lex_less|lex_lesseq|strict_lex2|value_precede|value_precede_chain)\b
      scope: support.function.mzn
    - match: \b(arg_sort|decreasing|increasing|sort)\b
      scope: support.function.mzn
    - match: \b(int_set_channel|inverse|inverse_set|link_set_to_booleans)\b
      scope: support.function.mzn
    - match: \b(among|at_least|at_most|at_most1|count|count_eq|count_geq|count_gt|count_leq|count_lt|count_neq|distribute|exactly|global_cardinality|global_cardinality_closed|global_cardinality_low_up|global_cardinality_low_up_closed)\b
      scope: support.function.mzn
    - match: \b(bin_packing|bin_packing_capa|bin_packing_load|diffn|diffn_k|diffn_nonstrict|diffn_nonstrict_k|geost|geost_bb|geost_smallest_bb|knapsack)\b
      scope: support.function.mzn
    - match: \b(alternative|cumulative|disjunctive|disjunctive_strict|span)\b
      scope: support.function.mzn
    - match: \b(regular|regular_nfa|table)\b
      scope: support.function.mzn
    - match: \b(not|\+|-)\b
      scope: keyword.operator.math.mzn
    - match: \b(<->|->|<-|\\/|xor|/\\)\b
      scope: keyword.operator.logical.mzn
    - match: \b(<|>|<=|>=|==|=|!=)\b
      scope: keyword.operator.math.mzn
    - match: \b(\+|-|\*|/|div|mod)\b
      scope: keyword.operator.math.mzn
    - match: \b(in|subset|superset|union|diff|symdiff|intersect)\b
      scope: keyword.operator.sets.mzn
    - match: \|\.\.|\+\+
      scope: keyword.operator.math.mzn
    - match: \b(true|false)\b
      scope: constant.language.mzn
    - match: '\b([_A-Za-z])(\w*)\b'
      scope: variable.other.mzn
    - match: '([+-]?)\d+(\.[^\.]\d*)?([eE][-+]?\d+)?'
      scope: constant.numeric.mzn
```
