### ISSUE TITLE
Built in Minify Support

### ISSUE THREAD

**Issue by imsus** [getzola/zola#542]
#### Problem

As the title says, currently Zola doesn't have built-in html minifier support. And as for comparison, Hugo has one by invoking:

```bash
$ hugo --minify
```

It will generate production-ready minified HTML (Inline Styles + Inline Scripts) pages.

#### Idea

By borrowing the idea from Hugo we can copy like:

```bash
$ zola build --minify
```

I'm not familiar with Rust ecosystem. So maybe using https://docs.rs/html-minifier/1.1.3/html_minifier/ is possible.

**Comment by Keats** [comment]
That's a good idea, although we already have minification for Sass. We can add HTML but not sure about JS/SVG/images, those are things you kind of want to add to do in-place instead of re-doing it everytime you build...

**Comment by chris-morgan** [comment]
I think it is reasonable to add optional extra roughly-lossless minification of at least HTML, JavaScript, CSS and SVG. For raster images, minification tends to be extremely slow, and I agree that doing them once and committing *that* is generally the right thing to do—but given image processing which can produce new artefacts, I think it is worthwhile anyway.

This is the point when you start mumbling about `make` and not throwing away artefacts obtained at great computational expense along with the `public` directory.

All minifiers will need the possibility of extra configuration; just look at [the options the npm html-minifier package has](https://www.npmjs.com/package/html-minifier#options-quick-reference), and I’ve definitely had situations where I’ve had to tweak them, and even tweak what I write to prevent it from ruining overly-clever HTML/CSS.

I don’t suggest using the minifier or html_minifier crate; they’re very rudimentary in what they can do, and not at all mature: they’ll be *super* fast by comparison, but not as effective as they could be, and they are more likely to break things as well.

A low-quality but very powerful first pass would be handing it off to third-party tools; I imagine something like this:

```toml
[[minify-pipeline]]
filename = "**/*.html"
command = "html-minifier --config-file html-minifier.config.js {file}"

[[minify-pipeline]]
filename = "**/*.png"
command = [
  "optipng -quiet -o7 -fix {file}",
  "advpng -q -z --shrink-insane {file}",
]
```

I thought of making this a general-purpose pipeline and adding an `optional` key which can be set to true for steps that don’t change the semantics (*viz.*, minification) or false for mandatory processing, but decided that wasn’t desirable due to the impact this whole approach is likely to have on build time, and that you now can’t do *anything* if you don’t have the third-party tool. Given this, defining it as specifically for minification (or expressed otherwise, production deployment) seems reasonable.

Here’s a possible simpler form:

```toml
[minify]
html = "html-minifier --config-file html-minifier.config.js {file}"
png = [
  "optipng -quiet -o7 -fix {file}",
  "advpng -q -z --shrink-insane {file}",
]
```

But I have concerns with this approach due to potentially significant ordering: e.g. you may want to minify JS, then inline it into HTML, and if the HTML is processed before the JS, then the HTML may contain unminified JS. But the TOML spec says “Key/value pairs within tables are not guaranteed to be in any specific order.”

I have not contemplated exactly how `static/processed_images` may fit into this scheme—I may want to feed all such images through cjpeg, for example.
