### ISSUE TITLE
Documentation Does Not Teach How To Configure And Use Translations

### ISSUE THREAD

**Issue by brunoczim** [getzola/zola#601]
# Documentation issue

## Summary
The documentation about [config file](https://www.getzola.org/documentation/getting-started/configuration/) says you can have a translation object:

```toml
# Optional translation object. The key if present should be a language code
[translations]
```
But I think HOW to configure translations are unclear. The docs says something about the key being a language code. But what is the value? A boolean? A description? Is it something like this?

```toml
# Optional translation object. The key if present should be a language code
[translations]
en = "English"
pt = "Portuguese"
de = "German"
```
And how do I organize my project to handle translations?

## Proposed solution
Consider adding example in the configuration page and also adding a page to teach how to handle translation.
