### ISSUE TITLE
Investigate lto & codegen units

### ISSUE THREAD

**Issue by Keats** [getzola/zola#785]
Right now the Cargo.toml has:

```toml
[profile.release]
lto = true
codegen-units = 1
```

in it for better performance at the cost of compilation speed.
Investigate how much additional time it takes & the perf difference.
This should be ideally done after https://github.com/getzola/zola/issues/782
