### ISSUE TITLE
[RFE] Allow customization of datetime format

### ISSUE THREAD

**Issue by rochacbruno** [getzola/zola#851]
Hi,

Currently the front-matter `date` variable must follow the `toml` date literal format, which is confusing for non-technical users.

example:

```toml
+++
title = "A new post on blog"
date = 2019-11-24T15:00:00Z
+++
```

When adding a new post on blog the writer must use the strict `%Y-%m-%dT%H:%M:%SZ`

My RFE is to add support for custom datetime format, chrono can handle different formats

https://github.com/chronotope/chrono

```rust
Utc.datetime_from_str("24/11/2019 12:00", "%d/%m/%Y %H:%M")
```

So for example, I can put on `config.toml`

```
datetime_format = "%d/%m/%Y %H:%M"
```

And now my new blog post can be

```toml
+++
title = "A new post on blog"
date = "24/11/2019 15:30"
+++
```
