### ISSUE TITLE
A paginator’s base_url ends with double slash when paginate_path is empty.

### ISSUE THREAD

**Issue by Zegnat** [getzola/zola#866]
# Bug Report

I was playing around with getting a simple content listing going, for this I did not want pagination to create a sub-directory. So having a number of pages in `/content/` I also created the following `_index.md` there:

```toml
+++
sort_by = "date"
paginate_by = 2 # For testing only
paginate_path = ""
+++
```

This results in `paginator.base_url` being `http://127.0.0.1:1111//` when running `zola serve`. I would expect just `http://127.0.0.1:1111/`.

## Environment

Zola version: 0.9.0
