### ISSUE TITLE
[Question] Markdown parser

### ISSUE THREAD

**Issue by noraj** [getzola/zola#987]
Which kind of Markdown parser is used?
By making a search on the documentation I found one occurrence of `CommonMark`. It's very good that Zola is using CommonMark :+1:  
But in the Configuration page of the doc I didn't see anything about being able to configure the markdown parser behavior.
As an example I will take the [hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it) plugin for Hexo staticgen, which is a wrapper of the CommonMark compliant [markdown-it](https://github.com/markdown-it/markdown-it) parser for Hexo.
It allows the user to configure some behavior about the rendering, for example:

```yaml
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: ''
```

Is there something similar in Zola?
